version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=book
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pmysql" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db:/var/lib/mysql

  app:
    ports:
      - "9080:9080"
    container_name: book
    environment:
      - DB_PASSWORD=mysql
    build:
      context: .
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db:
    driver: local